server:
  port: 8082
  servlet:
    context-path: '/product-store'

spring:
  application:
    name: product-store
#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/product-store
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

  flyway:
    schemas: users

logging:
  level:
    com.ecommerce: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
